### ISSUE TITLE
建立用户社群

### ISSUE THREAD

**Issue by chmod777john** [Milvoid/SJTU-Annual-Eat#10]
Hello 作者你好！

我在定时扫描全 Github 的优质潜力仓库 https://github.com/chmod777john/github-hunter

过去两天内，你的项目 Github star 增速放在全站排名都很靠前，被我扫到了。（基本算法是先讲所有 Github 仓库按照近两天获得的 star 排序，结果的前1000条再按创建时间排序，您的项目此时排全网第三）

有个小建议，可以弄个用户社群。看起来这个项目是专为交大学生设计的便利小公具，我觉得可以弄一个群，让大家可以实时地反馈意见，并且在群里讨论可以产生一点头脑风暴的效果，从而讨论出一些有价值的需求。

![image](https://github.com/user-attachments/assets/48419567-3d15-4c4d-a212-b06f9c74a5e2)

如作者需要，我将转移群管理 ^_^

**Comment by Milvoid** [comment]
非常感谢您的好意，我们已经有一个成熟的论坛用于讨论了，应该不会需要这个微信群聊
