### ISSUE TITLE
Merge generate-poster.py and Annual-Report.py

### ISSUE THREAD

**Issue by havedifficultyinfindingnames** [Milvoid/SJTU-Annual-Eat#13]
几乎是同一个逻辑写了两份，就因为生成html需要加标签的语法。。。可以想办法合并么？
此外在我电脑上poster里的pie-chart没有生成，我不太熟悉，不知道为什么。单步调试中能看到所有的html_data数据输入都是好的，但是最后图没有。

**Comment by Milvoid** [comment]
分析逻辑确实是差不多的，不过生成海报是后面加的新功能，作为可选功能就单放一个文件吧，应该问题不大
这个海报生成我也不熟地方，我自己测试跑了一遍貌似是没有问题的
